// src/components/dashboard/LearningFeed.tsx
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BookOpen, Zap, Users } from "lucide-react";

// This is placeholder data. In the future, this will be dynamically generated by the AI.
const feedItems = [
  {
    type: "Recommended Lesson",
    title: "Mastering Photosynthesis",
    description:
      "Dive deep into how plants create their own food. This lesson includes interactive videos and a short quiz.",
    icon: <BookOpen className="h-6 w-6 text-green-500" />,
    cta: "Start Lesson",
    ctaColor: "bg-green-500 hover:bg-green-500/90",
  },
  {
    type: "Daily Challenge",
    title: "Algebra Quick-Fire",
    description:
      "Solve 5 algebraic equations against the clock. Can you beat your previous best time?",
    icon: <Zap className="h-6 w-6 text-yellow-500" />,
    cta: "Take Challenge",
    ctaColor: "bg-yellow-500 hover:bg-yellow-500/90",
  },
  {
    type: "Community Highlight",
    title: "New Discussion in 'SHS 2 Science'",
    description:
      "Your study circle is discussing the practical applications of Newton's Laws. Join the conversation!",
    icon: <Users className="h-6 w-6 text-blue-500" />,
    cta: "View Discussion",
    ctaColor: "bg-blue-500 hover:bg-blue-500/90",
  },
];

export const LearningFeed = () => {
  return (
    <div className="space-y-6">
      {feedItems.map((item, index) => (
        <Card
          key={index}
          className="bg-white shadow-sm hover:shadow-md transition-shadow"
        >
          <CardHeader className="flex flex-row items-start justify-between">
            <div className="flex items-center space-x-4">
              <div className="p-3 bg-slate-100 rounded-full">{item.icon}</div>
              <div>
                <CardDescription>{item.type}</CardDescription>
                <CardTitle className="text-xl">{item.title}</CardTitle>
              </div>
            </div>
            <Button className={`${item.ctaColor} text-white`}>
              {item.cta}
            </Button>
          </CardHeader>
          <CardContent>
            <p className="text-slate-600 ml-16">{item.description}</p>
          </CardContent>
        </Card>
      ))}
    </div>
  );
};
